spring:
  datasource: #데이터베이스 수정해야함!
    url: jdbc:mysql://localhost:3306/board?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: youngwo1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
